[build]
builder = "nixpacks"

[deploy]
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 