[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Build phases for frontend integration
[phases.setup]
nixPkgs = ["python311", "nodejs", "npm"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/static",
  "cp -r frontend/build/* backend/static/"
] 